### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by ManarOmari** [ManarOmari/Project-1-Setup-and-mobile-version-skeleton#14]

**Comment by Sajeelzafar** [comment]
- In popupWindow.js file, you have to use fully and descriptive name for variables, like replace "const x = window.matchMedia('(min-width: 768px)');" with a meaningful variable.
- In the localstorage.js file, on line 9, the name variable is not recognized due to undesired spacing in the index file between lines 266 and 267.
